package org.jetbrains.kotlinx.jupyter.widget.generator

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.decodeFromJsonElement
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.encodeToJsonElement
import kotlinx.serialization.json.intOrNull
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.div
import kotlin.io.path.exists
import kotlin.io.path.readText
import kotlin.io.path.writeText

private const val GENERATED_NOTICE = """// Generated by widgets-generator. Do not edit manually."""

private const val WIDGETS_PACKAGE = "org.jetbrains.kotlinx.jupyter.widget"
private const val WIDGET_TYPES_PACKAGE = "$WIDGETS_PACKAGE.model.types"
private const val WIDGET_LIBRARY_PACKAGE = "$WIDGETS_PACKAGE.library"

private val hiddenAttributeNames =
    setOf(
        "_model_name",
        "_model_module",
        "_model_module_version",
        "_view_name",
        "_view_module",
        "_view_module_version",
    )

@Serializable
private data class WidgetSchema(
    val attributes: List<AttributeSchema>,
    val model: WidgetTypeSchema,
    val view: WidgetTypeSchema,
)

@Serializable
private data class WidgetTypeSchema(
    val module: String,
    val name: String?,
    val version: String,
)

@Serializable
private data class AttributeSchema(
    val name: String,
    val type: AttributeType,
    val default: JsonElement,
    @SerialName("allow_none") val allowNone: Boolean = false,
    val enum: List<String> = emptyList(),
    val help: String = "",
    val items: AttributeItems? = null,
    val widget: String? = null,
    @SerialName("union_attributes") val unionAttributes: List<JsonObject> = emptyList(),
)

@Serializable
private data class AttributeItems(
    val type: AttributeType,
    val widget: String? = null,
)

private object AttributeTypeSerializer {
    fun serialize(type: AttributeType): JsonElement =
        when (type) {
            is AttributeType.Single -> JsonPrimitive(type.name)
            is AttributeType.Union -> Json.encodeToJsonElement(type.options.map { serialize(it) })
        }
}

@Serializable(with = AttributeType.Companion::class)
private sealed class AttributeType {
    data class Single(
        val name: String,
    ) : AttributeType()

    data class Union(
        val options: List<Single>,
    ) : AttributeType()

    companion object : kotlinx.serialization.KSerializer<AttributeType> {
        private val delegate = JsonElement.serializer()

        override val descriptor = delegate.descriptor

        override fun deserialize(decoder: kotlinx.serialization.encoding.Decoder): AttributeType =
            when (val element = delegate.deserialize(decoder)) {
                is JsonPrimitive -> Single(element.content)
                else -> {
                    val options = Json.decodeFromJsonElement<List<JsonPrimitive>>(element)
                    Union(options.map { Single(it.content) })
                }
            }

        override fun serialize(
            encoder: kotlinx.serialization.encoding.Encoder,
            value: AttributeType,
        ) {
            encoder.encodeSerializableValue(delegate, AttributeTypeSerializer.serialize(value))
        }
    }
}

public fun main() {
    val projectRoot =
        Path
            .of(".")
            .toAbsolutePath()
            .normalize()
            .parent
            ?.parent
            ?.parent
            ?: error("Unable to resolve project root")

    val generator = WidgetGenerator(projectRoot)
    generator.generate()
}

private class WidgetGenerator(
    projectRoot: Path,
) {
    private val json = Json { ignoreUnknownKeys = true }

    private val schemaPath = projectRoot / "integrations/widgets/widgets-generator/schema.json"
    private val apiOutput = projectRoot / "integrations/widgets/widgets-api/src/generated/kotlin"
    private val jupyterOutput = projectRoot / "integrations/widgets/widgets-jupyter/src/generated/kotlin"

    fun generate() {
        val schemaText = schemaPath.readText()
        val widgets = json.decodeFromString<List<WidgetSchema>>(schemaText)

        recreateDirectory(apiOutput)
        recreateDirectory(jupyterOutput)

        val widgetInfos = widgets.map { it.toInfo() }
        widgetInfos.forEach { generateWidgetFile(it) }
        generateFactoryRegistry(widgetInfos)
        generateJupyterHelpers(widgetInfos)
    }

    private fun WidgetSchema.toInfo(): WidgetInfo {
        val baseName =
            model.name?.removeSuffix("Model")
                ?: view.name?.removeSuffix("View")
                ?: error("Either model or view name must be specified")
        val className = if (baseName.endsWith("Widget")) baseName else "${baseName}Widget"
        val functionName = baseName.toCamelCase()
        return WidgetInfo(baseName, className, functionName, this)
    }

    private fun generateWidgetFile(info: WidgetInfo) {
        val packageName = "$WIDGETS_PACKAGE.library"
        val filePath = apiOutput / packageName.replace('.', '/') / "${info.className}.kt"
        filePath.parent.createDirectories()

        val builder = StringBuilder()
        val imports =
            sortedSetOf<String>().apply {
                for (importName in listOf(
                    "WidgetManager",
                    "model.DefaultWidgetFactory",
                    "model.DefaultWidgetModel",
                    "model.WidgetSpec",
                    "model.createAndRegisterWidget",
                )) {
                    add("$WIDGETS_PACKAGE.$importName")
                }
            }

        val helperDeclarations = mutableListOf<String>()
        val properties =
            info.schema.attributes.mapNotNull { attribute ->
                if (attribute.name in hiddenAttributeNames) return@mapNotNull null
                createProperty(attribute, info, helperDeclarations, imports)
            }

        builder.appendLine(GENERATED_NOTICE)
        builder.appendLine("package $packageName")
        builder.appendLine()
        if (imports.isNotEmpty()) {
            imports.forEach { builder.appendLine("import $it") }
            builder.appendLine()
        }

        helperDeclarations.forEach { declaration ->
            builder.appendLine(declaration)
            builder.appendLine()
        }

        val specName = "${info.functionName}Spec"
        builder.appendLine("private val $specName = WidgetSpec(")
        builder.appendLine("    modelName = \"${info.schema.model.name}\",")
        builder.appendLine("    modelModule = \"${info.schema.model.module}\",")
        builder.appendLine("    modelModuleVersion = \"${info.schema.model.version}\",")
        builder.appendLine("    viewName = \"${info.schema.view.name}\",")
        builder.appendLine("    viewModule = \"${info.schema.view.module}\",")
        builder.appendLine("    viewModuleVersion = \"${info.schema.view.version}\",")
        builder.appendLine(")")
        builder.appendLine()

        builder.appendLine(
            "public fun WidgetManager.${info.functionName}(): ${info.className} = createAndRegisterWidget(${info.className}.Factory)",
        )
        builder.appendLine()
        builder.appendLine("public class ${info.className} internal constructor(")
        builder.appendLine("    widgetManager: WidgetManager,")
        builder.appendLine(") : DefaultWidgetModel($specName, widgetManager) {")
        builder.appendLine("    internal object Factory : DefaultWidgetFactory<${info.className}>($specName, ::${info.className})")
        builder.appendLine()

        properties.forEach { builder.appendLine(it) }

        builder.appendLine("}")

        filePath.writeText(builder.toString())
    }

    private fun createProperty(
        attribute: AttributeSchema,
        widgetInfo: WidgetInfo,
        helperDeclarations: MutableList<String>,
        imports: MutableSet<String>,
    ): String {
        val typeInfo = attribute.toTypeInfo(widgetInfo, helperDeclarations, imports)
        return buildString {
            append("    public var ${attribute.name.toPascalCase().toCamelCase()}: ${typeInfo.kotlinType} by ")
            append(typeInfo.delegate)
        }
    }

    private fun AttributeSchema.toTypeInfo(
        widgetInfo: WidgetInfo,
        helperDeclarations: MutableList<String>,
        imports: MutableSet<String>,
    ): TypeInfo =
        when (type) {
            is AttributeType.Single -> toSingleTypeInfo(widgetInfo, helperDeclarations, imports)
            is AttributeType.Union -> toUnionTypeInfo(widgetInfo, helperDeclarations, imports)
        }

    private fun AttributeSchema.toUnionTypeInfo(
        widgetInfo: WidgetInfo,
        helperDeclarations: MutableList<String>,
        imports: MutableSet<String>,
    ): TypeInfo {
        val nameForType = "${widgetInfo.className}${name.toPascalCase()}UnionType"
        val optionTypes =
            when (type) {
                is AttributeType.Single -> listOf(AttributeSchema(name, type, default, allowNone, enum, help, items, widget))
                is AttributeType.Union ->
                    type.options.map { opt ->
                        AttributeSchema(name, opt, default, allowNone, enum, help, items, widget)
                    }
            }

        val candidateInfos =
            optionTypes.map { candidate ->
                candidate.copy(unionAttributes = emptyList()).toSingleTypeInfo(widgetInfo, helperDeclarations, imports)
            }

        val serializerSelector = "{ value ->\n        when (value) {\n${candidateInfos.joinToString(separator = "\n") { info ->
            "            is ${info.kotlinTypeWithoutNullability} -> ${info.propertyTypeExpr}"
        }}\n            else -> ${candidateInfos.last().propertyTypeExpr}\n        }\n    }"

        imports.add("$WIDGET_TYPES_PACKAGE.compound.UnionType")
        val deserializers =
            candidateInfos.joinToString(", ") {
                it.propertyTypeExpr
            }
        val unionDeclaration =
            buildString {
                appendLine("private val $nameForType = UnionType<Any>(")
                appendLine("    name = \"$name\",")
                appendLine("    default = ${candidateInfos.first().defaultValue},")
                appendLine("    serializerSelector = $serializerSelector,")
                appendLine("    deserializers = listOf($deserializers),")
                appendLine(")")
            }

        helperDeclarations += unionDeclaration

        val defaultValue = candidateInfos.first().defaultValue
        return TypeInfo("Any", "prop(\"$name\", $nameForType, $defaultValue)", nameForType, defaultValue)
    }

    private fun AttributeSchema.toSingleTypeInfo(
        widgetInfo: WidgetInfo,
        helperDeclarations: MutableList<String>,
        imports: MutableSet<String>,
    ): TypeInfo {
        if (enum.isNotEmpty()) {
            return toEnumType(widgetInfo, helperDeclarations, imports)
        }

        return when ((type as AttributeType.Single).name) {
            "string" -> basicType("String", "stringProp", imports, this)
            "bool" -> basicType("Boolean", "boolProp", imports, this)
            "int" -> basicType("Int", "intProp", imports, this)
            "float" -> basicType("Double", "doubleProp", imports, this)
            "bytes" -> basicType("ByteArray", "bytesProp", imports, this)
            "Datetime" -> timedType("java.time.Instant", "$WIDGET_TYPES_PACKAGE.datetime.DatetimeType", imports)
            "Date" -> timedType("java.time.LocalDate", "$WIDGET_TYPES_PACKAGE.datetime.DateType", imports)
            "Time" -> timedType("java.time.LocalTime", "$WIDGET_TYPES_PACKAGE.datetime.TimeType", imports)
            "reference" -> referenceType(imports)
            "object" -> objectType(imports)
            "array" -> arrayType(widgetInfo, helperDeclarations, imports)
            else -> error("Unsupported type $type")
        }
    }

    private fun AttributeSchema.objectType(imports: MutableSet<String>): TypeInfo {
        imports.add("$WIDGET_TYPES_PACKAGE.compound.RawObjectType")
        val nullable = allowNone || default is JsonNull
        val kotlinType = if (nullable) "Map<String, Any?>?" else "Map<String, Any?>"
        val propertyTypeExpr =
            if (nullable) {
                imports.add("$WIDGET_TYPES_PACKAGE.compound.NullableType")
                "NullableType(RawObjectType)"
            } else {
                "RawObjectType"
            }
        val delegate = "prop(\"$name\", $propertyTypeExpr, ${if (nullable) "null" else "emptyMap()"})"
        return TypeInfo(kotlinType, delegate, propertyTypeExpr, if (nullable) "null" else "emptyMap()")
    }

    private fun AttributeSchema.referenceType(imports: MutableSet<String>): TypeInfo {
        val targetClass = referencedClassName()
        val defaultValue =
            if ((default as? JsonPrimitive)?.content == "reference to new instance") {
                "widgetManager.${targetClass.toCamelCase().removeSuffix("Widget")}()"
            } else {
                "null"
            }

        if (targetClass == "WidgetModel") {
            imports.add("$WIDGETS_PACKAGE.model.WidgetModel")
        }
        imports.add("$WIDGET_TYPES_PACKAGE.widget.WidgetReferenceType")
        imports.add("$WIDGET_TYPES_PACKAGE.compound.NullableType")

        val kotlinType = "$targetClass?"
        val delegate = "widgetProp(\"$name\", $defaultValue)"
        return TypeInfo(kotlinType, delegate, "WidgetReferenceType<$targetClass>()", defaultValue)
    }

    private fun AttributeSchema.arrayType(
        widgetInfo: WidgetInfo,
        helperDeclarations: MutableList<String>,
        imports: MutableSet<String>,
    ): TypeInfo {
        val elementInfo =
            if (items == null) {
                imports.add("$WIDGET_TYPES_PACKAGE.primitive.AnyType")
                TypeInfo("Any?", "prop(\"$name-item\", AnyType, null)", "AnyType", "null")
            } else {
                items.toElementType(widgetInfo, helperDeclarations, imports)
            }
        imports.add("$WIDGET_TYPES_PACKAGE.compound.ArrayType")
        val propertyTypeExpr = "ArrayType(${elementInfo.propertyTypeExpr})"
        val defaultValue = defaultArrayValue(elementInfo.kotlinType, default)
        val delegate = "prop(\"$name\", $propertyTypeExpr, $defaultValue)"
        return TypeInfo("List<${elementInfo.kotlinType}>", delegate, propertyTypeExpr, defaultValue)
    }

    private fun AttributeItems.toElementType(
        widgetInfo: WidgetInfo,
        helperDeclarations: MutableList<String>,
        imports: MutableSet<String>,
    ): TypeInfo {
        val schema = AttributeSchema(name = "item", type = type, default = JsonNull, widget = widget)
        return schema.toSingleTypeInfo(widgetInfo, helperDeclarations, imports)
    }

    private fun AttributeSchema.timedType(
        kotlinType: String,
        typeImport: String,
        imports: MutableSet<String>,
    ): TypeInfo {
        imports.add(typeImport)
        val propertyTypeExpr = typeImport.substringAfterLast('.')
        val nullable = allowNone || default is JsonNull
        val actualTypeExpr =
            if (nullable) {
                imports.add("$WIDGET_TYPES_PACKAGE.compound.NullableType")
                "NullableType($propertyTypeExpr)"
            } else {
                propertyTypeExpr
            }
        val kotlinTypeName = if (nullable) "$kotlinType?" else kotlinType
        val defaultValue = renderLiteral(kotlinTypeName, default)
        val delegate = "prop(\"$name\", $actualTypeExpr, $defaultValue)"
        return TypeInfo(kotlinTypeName, delegate, actualTypeExpr, defaultValue)
    }

    private fun basicType(
        kotlinType: String,
        delegateName: String,
        imports: MutableSet<String>,
        attribute: AttributeSchema,
    ): TypeInfo {
        val nullable = attribute.allowNone || attribute.default is JsonNull
        val typeName = if (nullable) "$kotlinType?" else kotlinType
        val defaultValue = renderLiteral(typeName, attribute.default)
        imports.add("$WIDGET_TYPES_PACKAGE.primitive.${kotlinType.toPrimitiveTypeName()}")
        return if (nullable) {
            imports.add("$WIDGET_TYPES_PACKAGE.compound.NullableType")
            val propertyTypeExpr = "NullableType(${kotlinType.toPrimitiveTypeName()})"
            val delegate = "prop(\"${attribute.name}\", $propertyTypeExpr, $defaultValue)"
            TypeInfo(typeName, delegate, propertyTypeExpr, defaultValue)
        } else {
            TypeInfo(typeName, "$delegateName(\"${attribute.name}\", $defaultValue)", kotlinType.toPrimitiveTypeName(), defaultValue)
        }
    }

    private fun AttributeSchema.toEnumType(
        widgetInfo: WidgetInfo,
        helperDeclarations: MutableList<String>,
        imports: MutableSet<String>,
    ): TypeInfo {
        val enumName = "${widgetInfo.className}${name.toPascalCase()}"
        imports.add("$WIDGET_TYPES_PACKAGE.enums.WidgetEnum")
        imports.add("$WIDGET_TYPES_PACKAGE.enums.WidgetEnumEntry")
        imports.add("$WIDGET_TYPES_PACKAGE.enums.WidgetEnumType")

        val entries =
            enum.joinToString("\n") { value ->
                val entryName = if (value.isEmpty()) "Default" else value.toPascalCase()
                "    public val $entryName: WidgetEnumEntry<$enumName> by entry(\"$value\")"
            }

        val enumDeclaration = "public object $enumName : WidgetEnum<$enumName>() {\n$entries\n}"
        helperDeclarations += enumDeclaration

        val defaultEntry = (default as? JsonPrimitive)?.content?.takeUnless { it == "null" }
        val nullable = allowNone || default is JsonNull
        val defaultExpression =
            when {
                defaultEntry == null -> "null"
                defaultEntry.isEmpty() -> "$enumName.Default"
                else -> "$enumName.${defaultEntry.toPascalCase()}"
            }

        val typeDefaultEntry = (defaultEntry ?: enum.first()).ifEmpty { "Default" }
        imports.add("$WIDGET_TYPES_PACKAGE.compound.NullableType")
        val typeExpr =
            if (nullable) {
                "NullableType(WidgetEnumType($enumName, $enumName.${typeDefaultEntry.toPascalCase()}))"
            } else {
                "WidgetEnumType($enumName, $enumName.${typeDefaultEntry.toPascalCase()})"
            }

        val kotlinType = if (nullable) "WidgetEnumEntry<$enumName>?" else "WidgetEnumEntry<$enumName>"
        val delegate = "prop(\"$name\", $typeExpr, $defaultExpression)"
        return TypeInfo(kotlinType, delegate, typeExpr, defaultExpression)
    }

    private fun AttributeSchema.referencedClassName(): String {
        val base = widget ?: error("Reference widget is not specified")
        if (base == "Widget") return "WidgetModel"
        if (base == "Axis") return "ControllerAxisWidget"
        return if (base.endsWith("Widget")) base else "${base}Widget"
    }

    private fun defaultArrayValue(
        elementKotlinType: String,
        value: JsonElement,
    ): String =
        if (value is kotlinx.serialization.json.JsonArray && value.isNotEmpty()) {
            val renderedItems = value.joinToString(", ") { renderLiteral(elementKotlinType, it) }
            "listOf($renderedItems)"
        } else {
            "emptyList()"
        }

    private fun renderLiteral(
        kotlinType: String,
        value: JsonElement,
    ): String =
        when {
            value is JsonNull -> "null"
            kotlinType == "ByteArray" || kotlinType == "ByteArray?" -> "byteArrayOf()"
            value is JsonPrimitive -> {
                if (value.isString) {
                    val quoted =
                        value.content
                            .replace("\\", "\\\\")
                            .replace("\"", "\\\"")
                    "\"$quoted\""
                } else {
                    val primitiveValue =
                        value.booleanOrNull
                            ?: value.intOrNull
                            ?: value.doubleOrNull
                            ?: error("Unsupported primitive value for $kotlinType: $value")
                    primitiveValue.toString()
                }
            }
            else -> error("Unsupported literal for $kotlinType: $value")
        }

    private fun String.toPrimitiveTypeName(): String =
        when (this) {
            "Int" -> "IntType"
            "Double" -> "FloatType"
            "Boolean" -> "BooleanType"
            "String" -> "StringType"
            "ByteArray" -> "BytesType"
            else -> error("Unsupported primitive type $this")
        }

    private fun generateFactoryRegistry(widgetInfos: List<WidgetInfo>) {
        val packageName = "$WIDGET_LIBRARY_PACKAGE.registry"
        val filePath = apiOutput / packageName.replace('.', '/') / "DefaultWidgetFactories.kt"
        filePath.parent.createDirectories()

        val sortedInfos = widgetInfos.sortedInImportsOrder { it.className }
        val content =
            buildString {
                appendLine(GENERATED_NOTICE)
                appendLine("package $packageName")
                appendLine()
                for (info in sortedInfos) {
                    appendLine("import $WIDGET_LIBRARY_PACKAGE.${info.className}")
                }
                appendLine("import $WIDGETS_PACKAGE.model.WidgetFactory")
                appendLine()
                appendLine("internal val defaultWidgetFactories = listOf<WidgetFactory<*>>(")
                for (info in sortedInfos) {
                    appendLine("    ${info.className}.Factory,")
                }
                appendLine(")")
            }

        filePath.writeText(content)
    }

    private fun generateJupyterHelpers(widgetInfos: List<WidgetInfo>) {
        val packageName = "$WIDGETS_PACKAGE.integration"
        val filePath = jupyterOutput / packageName.replace('.', '/') / "JupyterWidgetLibrary.kt"
        filePath.parent.createDirectories()

        val sortedInfos = widgetInfos.sortedInImportsOrder { it.functionName }
        val content =
            buildString {
                appendLine(GENERATED_NOTICE)
                appendLine("package $packageName")
                appendLine()
                for (info in widgetInfos.sortedInImportsOrder { it.className }) {
                    appendLine("import $WIDGET_LIBRARY_PACKAGE.${info.className}")
                }
                for (info in sortedInfos) {
                    appendLine("import $WIDGET_LIBRARY_PACKAGE.${info.functionName}")
                }
                appendLine()
                for (info in sortedInfos) {
                    appendLine("public fun ${info.functionName}Widget(): ${info.className} = globalWidgetManager.${info.functionName}()")
                    appendLine()
                }
            }

        filePath.writeText(content)
    }

    private fun <T> List<T>.sortedInImportsOrder(representAsString: (T) -> String): List<T> =
        sortedWith { a, b ->
            when {
                representAsString(a).startsWith(representAsString(b)) -> 1
                representAsString(b).startsWith(representAsString(a)) -> -1
                else -> representAsString(a).compareTo(representAsString(b))
            }
        }

    private fun recreateDirectory(path: Path) {
        if (path.exists()) {
            Files
                .walk(path)
                .sorted(Comparator.reverseOrder())
                .forEach(Files::delete)
        }
        path.createDirectories()
    }
}

private data class WidgetInfo(
    val baseName: String,
    val className: String,
    val functionName: String,
    val schema: WidgetSchema,
)

private val commonAbbreviations =
    setOf(
        "html",
    )

private fun String.toCamelCase(): String {
    if (isEmpty()) return this
    if (length == 1) return lowercase()
    val abbreviation = commonAbbreviations.find { startsWith(it, ignoreCase = true) }
    val suffixStartIndex =
        if (abbreviation == null) {
            var index = 1
            while (index < length && this[index].isUpperCase()) {
                index++
            }
            index
        } else {
            abbreviation.length
        }

    val prefix = substring(0, suffixStartIndex)
    val rest = substring(suffixStartIndex)
    return prefix.lowercase() + rest
}

private fun String.toPascalCase(): String =
    split('_', '-', ' ').joinToString("") { part ->
        part.lowercase().replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
    }

private data class TypeInfo(
    val kotlinType: String,
    val delegate: String,
    val propertyTypeExpr: String,
    val defaultValue: String,
) {
    val kotlinTypeWithoutNullability: String get() = kotlinType.removeSuffix("?")
}
